{% set name = "setu" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: bfcce1a41d3d59bd07c4592c487aaf87928389d2a2e604f1b7b191948057e984

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - deprecated >=1.2.13,<2.0.0
    - marshmallow >=3.14.1,<4.0.0
    - marshmallow-oneofschema >=3.0.1,<4.0.0
    - pip
    - pyjwt >=2.4.0,<3.0.0
    - python
    - requests >=2.27.1,<3.0.0
  run:
    - deprecated >=1.2.13,<2.0.0
    - marshmallow >=3.14.1,<4.0.0
    - marshmallow-oneofschema >=3.0.1,<4.0.0
    - pyjwt >=2.4.0,<3.0.0
    - python>=3.7
    - requests >=2.27.1,<3.0.0

test:
  imports:
    - setu
    - tests

about:
  home: "https://github.com/jnarayan81/setu"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Robust assembly of the SARS-CoV-2 genome"
  doc_url: https://github.com/jnarayan81/setu/README.md
  dev_url: https://github.com/jnarayan81/setu

extra:
  recipe-maintainers:
    - jnarayan81
    - nityendra21
